name: File type finder
on: [pull_request]
jobs:
  list:
    name: File type finder
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: File type finder action
        id: ftf
        uses: ab185508/file-type-finder@main
        with:
          path: "/"
          type: ".yml"

      - name: Echo results (For visualization)
        run: |
          echo ${{ steps.ftf.outputs.names }}
          echo ${{ steps.ftf.outputs.paths }}